//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Проекты
    {
        public int ProektID { get; set; }
        public string NazvanieProekta { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> DateSroki { get; set; }
        public Nullable<int> SotrudnikId { get; set; }
        public Nullable<int> ZakazchikID { get; set; }
        public Nullable<int> SpezializaziaID { get; set; }
        public Nullable<int> cena { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Специализация Специализация { get; set; }
    }
}
